// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgd7EN1_V7-htL1Dbp3uVz6-R16zcP1Vw',
    appId: '1:976363472569:web:36556d58c682f1e14d7d68',
    messagingSenderId: '976363472569',
    projectId: 'fir-flutter-codelab-f42c8',
    authDomain: 'fir-flutter-codelab-f42c8.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-f42c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB4d1SVD0ssyFq0wiWcI8w0br2ZBuXorg',
    appId: '1:976363472569:android:c405219f99a297f34d7d68',
    messagingSenderId: '976363472569',
    projectId: 'fir-flutter-codelab-f42c8',
    storageBucket: 'fir-flutter-codelab-f42c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqY5HkmEpdEgR-ZFsmrIcXvqTXfEJbkW8',
    appId: '1:976363472569:ios:e04bfb62dc7ed72a4d7d68',
    messagingSenderId: '976363472569',
    projectId: 'fir-flutter-codelab-f42c8',
    storageBucket: 'fir-flutter-codelab-f42c8.firebasestorage.app',
    iosClientId: '976363472569-2tp85qt926593j3nfqrakdema0h2knq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqY5HkmEpdEgR-ZFsmrIcXvqTXfEJbkW8',
    appId: '1:976363472569:ios:e04bfb62dc7ed72a4d7d68',
    messagingSenderId: '976363472569',
    projectId: 'fir-flutter-codelab-f42c8',
    storageBucket: 'fir-flutter-codelab-f42c8.firebasestorage.app',
    iosClientId: '976363472569-2tp85qt926593j3nfqrakdema0h2knq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
